/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},e="undefined"!==typeof module&&module.exports,b="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,d=function(){for(var b,c=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),
"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],d=0,f=c.length,e={};d<f;d++)if((b=c[d])&&b[1]in a){for(d=0;d<b.length;d++)e[c[0][d]]=
b[d];return e}return!1}(),l={change:d.fullscreenchange,error:d.fullscreenerror},g={request:function(e){var c=d.requestFullscreen;e=e||a.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))e[c]();else e[c](b&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){a[d.exitFullscreen]()},toggle:function(a){this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},on:function(b,c){var d=l[b];d&&a.addEventListener(d,c,!1)},off:function(b,
c){var d=l[b];d&&a.removeEventListener(d,c,!1)},raw:d};d?(Object.defineProperties(g,{isFullscreen:{get:function(){return!!a[d.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[d.fullscreenElement]}},enabled:{enumerable:!0,get:function(){return!!a[d.fullscreenEnabled]}}}),e?module.exports=g:window.screenfull=g):e?module.exports=!1:window.screenfull=!1})();
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],e=0;e<a.length;e++){var b=document.createElement("meta");b.name=a[e].name;b.content=a[e].content;var d=window.document.head.querySelector('meta[name="'+b.name+'"]');d&&d.parentNode.removeChild(d);window.document.head.appendChild(b)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"!==platform.name.toLowerCase()&&(buildIOSFullscreenPanel(),buildIOSMeta())});jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"!==platform.name.toLowerCase()&&iosResize()});
(function(){function a(a){a=String(a);return a.charAt(0).toUpperCase()+a.slice(1)}function e(a,b){var c=-1,f=a?a.length:0;if("number"==typeof f&&-1<f&&f<=w)for(;++c<f;)b(a[c],c,a);else d(a,b)}function b(b){b=String(b).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(b)?b:a(b)}function d(a,b){for(var c in a)z.call(a,c)&&b(a[c],c,a)}function l(b){return null==b?a(b):B.call(b).slice(8,-1)}function g(a,b){var c=null!=a?typeof a[b]:"number";return!/^(?:boolean|number|string|undefined)$/.test(c)&&
("object"==c?!!a[b]:!0)}function k(a){return String(a).replace(/([ -])(?!$)/g,"$1?")}function c(a,b){var c=null;e(a,function(d,f){c=b(c,d,f,a)});return c}function m(a){function f(d){return c(d,function(c,d){var f=d.pattern||k(d);!c&&(c=RegExp("\\b"+f+" *\\d+[.\\w_]*","i").exec(a)||RegExp("\\b"+f+" *\\w+-[\\w]*","i").exec(a)||RegExp("\\b"+f+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(a))&&((c=String(d.label&&!RegExp(f,"i").test(d.label)?d.label:c).split("/"))[1]&&!/[\d.]+/.test(c[0])&&(c[0]+=
" "+c[1]),d=d.label||d,c=b(c[0].replace(RegExp(f,"i"),d).replace(RegExp("; *(?:"+d+"[_-])?","i")," ").replace(RegExp("("+d+")[-_.]?(\\w)","i"),"$1 $2")));return c})}function e(b){return c(b,function(b,c){return b||(RegExp(c+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(a)||0)[1]||null})}var n=t,p=a&&"object"==typeof a&&"String"!=l(a);p&&(n=a,a=null);var D=n.navigator||{},v=D.userAgent||"";a||(a=v);var I=p?!!D.likeChrome:/\bChrome\b/.test(a)&&!/internal|\n/i.test(B.toString()),
w=p?"Object":"ScriptBridgingProxyObject",z=p?"Object":"Environment",H=p&&n.java?"JavaPackage":l(n.java),Q=p?"Object":"RuntimeObject";z=(H=/\bJava/.test(H)&&n.java)&&l(n.environment)==z;var R=H?"a":"\u03b1",S=H?"b":"\u03b2",N=n.document||{},E=n.operamini||n.opera,K=r.test(K=p&&E?E["[[Class]]"]:l(E))?K:E=null,h,L=a;p=[];var M=null,F=a==v;v=F&&E&&"function"==typeof E.version&&E.version();var x=function(b){return c(b,function(b,c){return b||RegExp("\\b"+(c.pattern||k(c))+"\\b","i").exec(a)&&(c.label||
c)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),q=function(b){return c(b,function(b,c){return b||RegExp("\\b"+(c.pattern||k(c))+"\\b","i").exec(a)&&(c.label||c)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),y=f([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),C=function(b){return c(b,function(b,c,d){return b||(c[y]||c[/^[a-z]+(?: +[a-z]+\b)*/i.exec(y)]||RegExp("\\b"+k(d)+"(?:\\b|\\w*\\d)","i").exec(a))&&d})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),u=function(d){return c(d,function(c,d){var f=d.pattern||k(d);if(!c&&(c=RegExp("\\b"+f+"(?:/[\\d.]+|[ \\w.]*)","i").exec(a))){var e=c,l=d.label||d,m={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};f&&l&&/^Win/i.test(e)&&!/^Windows Phone /i.test(e)&&(m=m[/[\d.]+$/.exec(e)])&&(e="Windows "+m);e=String(e);f&&l&&(e=e.replace(RegExp(f,"i"),l));c=e=b(e.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return c})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);x&&(x=[x]);C&&!y&&(y=f([C]));if(h=/\bGoogle TV\b/.exec(y))y=h[0];/\bSimulator\b/i.test(a)&&(y=(y?y+" ":"")+"Simulator");"Opera Mini"==q&&/\bOPiOS\b/.test(a)&&p.push("running in Turbo/Uncompressed mode");"IE"==q&&/\blike iPhone OS\b/.test(a)?(h=m(a.replace(/like iPhone OS/,"")),C=h.manufacturer,y=h.product):/^iP/.test(y)?(q||(q="Safari"),u="iOS"+((h=/ OS ([\d_]+)/i.exec(a))?" "+h[1].replace(/_/g,"."):"")):"Konqueror"!=q||/buntu/i.test(u)?C&&"Google"!=C&&(/Chrome/.test(q)&&
!/\bMobile Safari\b/i.test(a)||/\bVita\b/.test(y))||/\bAndroid\b/.test(u)&&/^Chrome/.test(q)&&/\bVersion\//i.test(a)?(q="Android Browser",u=/\bAndroid\b/.test(u)?u:"Android"):"Silk"==q?(/\bMobi/i.test(a)||(u="Android",p.unshift("desktop mode")),/Accelerated *= *true/i.test(a)&&p.unshift("accelerated")):"PaleMoon"==q&&(h=/\bFirefox\/([\d.]+)\b/.exec(a))?p.push("identifying as Firefox "+h[1]):"Firefox"==q&&(h=/\b(Mobile|Tablet|TV)\b/i.exec(a))?(u||(u="Firefox OS"),y||(y=h[1])):!q||(h=!/\bMinefield\b/i.test(a)&&
/\b(?:Firefox|Safari)\b/.exec(q))?(q&&!y&&/[\/,]|^[^(]+?\)/.test(a.slice(a.indexOf(h+"/")+8))&&(q=null),(h=y||C||u)&&(y||C||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(u))&&(q=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(u)?u:h)+" Browser")):"Electron"==q&&(h=(/\bChrome\/([\d.]+)\b/.exec(a)||0)[1])&&p.push("Chromium "+h):u="Kubuntu";v||(v=e(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",k(q),"(?:Firefox|Minefield|NetFront)"]));
if(h="iCab"==x&&3<parseFloat(v)&&"WebKit"||/\bOpera\b/.test(q)&&(/\bOPR\b/.test(a)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(a)&&!/^(?:Trident|EdgeHTML)$/.test(x)&&"WebKit"||!x&&/\bMSIE\b/i.test(a)&&("Mac OS"==u?"Tasman":"Trident")||"WebKit"==x&&/\bPlayStation\b(?! Vita\b)/i.test(q)&&"NetFront")x=[h];"IE"==q&&(h=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(a)||0)[1])?(q+=" Mobile",u="Windows Phone "+(/\+$/.test(h)?h:h+".x"),p.unshift("desktop mode")):/\bWPDesktop\b/i.test(a)?(q="IE Mobile",u="Windows Phone 8.x",
p.unshift("desktop mode"),v||(v=(/\brv:([\d.]+)/.exec(a)||0)[1])):"IE"!=q&&"Trident"==x&&(h=/\brv:([\d.]+)/.exec(a))&&(q&&p.push("identifying as "+q+(v?" "+v:"")),q="IE",v=h[1]);if(F){if(g(n,"global"))if(H&&(h=H.lang.System,L=h.getProperty("os.arch"),u=u||h.getProperty("os.name")+" "+h.getProperty("os.version")),z){try{v=n.require("ringo/engine").version.join("."),q="RingoJS"}catch(P){(h=n.system)&&h.global.system==n.system&&(q="Narwhal",u||(u=h[0].os||null))}q||(q="Rhino")}else"object"==typeof n.process&&
!n.process.browser&&(h=n.process)&&("object"==typeof h.versions&&("string"==typeof h.versions.electron?(p.push("Node "+h.versions.node),q="Electron",v=h.versions.electron):"string"==typeof h.versions.nw&&(p.push("Chromium "+v,"Node "+h.versions.node),q="NW.js",v=h.versions.nw)),q||(q="Node.js",L=h.arch,u=h.platform,v=(v=/[\d.]+/.exec(h.version))?v[0]:null));else l(h=n.runtime)==w?(q="Adobe AIR",u=h.flash.system.Capabilities.os):l(h=n.phantom)==Q?(q="PhantomJS",v=(h=h.version||null)&&h.major+"."+h.minor+
"."+h.patch):"number"==typeof N.documentMode&&(h=/\bTrident\/(\d+)/i.exec(a))?(v=[v,N.documentMode],(h=+h[1]+4)!=v[1]&&(p.push("IE "+v[1]+" mode"),x&&(x[1]=""),v[1]=h),v="IE"==q?String(v[1].toFixed(1)):v[0]):"number"==typeof N.documentMode&&/^(?:Chrome|Firefox)\b/.test(q)&&(p.push("masking as "+q+" "+v),q="IE",v="11.0",x=["Trident"],u="Windows");u=u&&b(u)}v&&(h=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(v)||/(?:alpha|beta)(?: ?\d)?/i.exec(a+";"+(F&&D.appMinorVersion))||/\bMinefield\b/i.test(a)&&
"a")&&(M=/b/i.test(h)?"beta":"alpha",v=v.replace(RegExp(h+"\\+?$"),"")+("beta"==M?S:R)+(/\d+\+?/.exec(h)||""));if("Fennec"==q||"Firefox"==q&&/\b(?:Android|Firefox OS)\b/.test(u))q="Firefox Mobile";else if("Maxthon"==q&&v)v=v.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(y))"Xbox 360"==y&&(u=null),"Xbox 360"==y&&/\bIEMobile\b/.test(a)&&p.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(q)&&(!q||y||/Browser|Mobi/.test(q))||"Windows CE"!=u&&!/Mobi/i.test(a))if("IE"==q&&F)try{null===n.external&&
p.unshift("platform preview")}catch(P){p.unshift("embedded")}else(/\bBlackBerry\b/.test(y)||/\bBB10\b/.test(a))&&(h=(RegExp(y.replace(/ +/g," *")+"/([.\\d]+)","i").exec(a)||0)[1]||v)?(h=[h,/BB10/.test(a)],u=(h[1]?(y=null,C="BlackBerry"):"Device Software")+" "+h[0],v=null):this!=d&&"Wii"!=y&&(F&&E||/Opera/.test(q)&&/\b(?:MSIE|Firefox)\b/i.test(a)||"Firefox"==q&&/\bOS X (?:\d+\.){2,}/.test(u)||"IE"==q&&(u&&!/^Win/.test(u)&&5.5<v||/\bWindows XP\b/.test(u)&&8<v||8==v&&!/\bTrident\b/.test(a)))&&!r.test(h=
m.call(d,a.replace(r,"")+";"))&&h.name&&(h="ing as "+h.name+((h=h.version)?" "+h:""),r.test(q)?(/\bIE\b/.test(h)&&"Mac OS"==u&&(u=null),h="identify"+h):(h="mask"+h,q=K?b(K.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(h)&&(u=null),F||(v=null)),x=["Presto"],p.push(h));else q+=" Mobile";if(h=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(a)||0)[1]){h=[parseFloat(h.replace(/\.(\d)$/,".0$1")),h];if("Safari"==q&&"+"==h[1].slice(-1))q="WebKit Nightly",M="alpha",v=h[1].slice(0,-1);else if(v==h[1]||v==(h[2]=
(/\bSafari\/([\d.]+\+?)/i.exec(a)||0)[1]))v=null;h[1]=(/\bChrome\/([\d.]+)/i.exec(a)||0)[1];537.36==h[0]&&537.36==h[2]&&28<=parseFloat(h[1])&&"WebKit"==x&&(x=["Blink"]);F&&(I||h[1])?(x&&(x[1]="like Chrome"),h=h[1]||(h=h[0],530>h?1:532>h?2:532.05>h?3:533>h?4:534.03>h?5:534.07>h?6:534.1>h?7:534.13>h?8:534.16>h?9:534.24>h?10:534.3>h?11:535.01>h?12:535.02>h?"13+":535.07>h?15:535.11>h?16:535.19>h?17:536.05>h?18:536.1>h?19:537.01>h?20:537.11>h?"21+":537.13>h?23:537.18>h?24:537.24>h?25:537.36>h?26:"Blink"!=
x?"27":"28")):(x&&(x[1]="like Safari"),h=(h=h[0],400>h?1:500>h?2:526>h?3:533>h?4:534>h?"4+":535>h?5:537>h?6:538>h?7:601>h?8:"8"));x&&(x[1]+=" "+(h+="number"==typeof h?".x":/[.+]/.test(h)?"":"+"));"Safari"==q&&(!v||45<parseInt(v))&&(v=h)}"Opera"==q&&(h=/\bzbov|zvav$/.exec(u))?(q+=" ",p.unshift("desktop mode"),"zvav"==h?(q+="Mini",v=null):q+="Mobile",u=u.replace(RegExp(" *"+h+"$"),"")):"Safari"==q&&/\bChrome\b/.exec(x&&x[1])&&(p.unshift("desktop mode"),q="Chrome Mobile",v=null,/\bOS X\b/.test(u)?(C=
"Apple",u="iOS 4.3+"):u=null);v&&0==v.indexOf(h=/[\d.]+$/.exec(u))&&-1<a.indexOf("/"+h+"-")&&(u=String(u.replace(h,"")).replace(/^ +| +$/g,""));x&&!/\b(?:Avant|Nook)\b/.test(q)&&(/Browser|Lunascape|Maxthon/.test(q)||"Safari"!=q&&/^iOS/.test(u)&&/\bSafari\b/.test(x[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(q)&&x[1])&&(h=x[x.length-1])&&p.push(h);p.length&&(p=["("+p.join("; ")+")"]);C&&y&&0>y.indexOf(C)&&p.push("on "+C);y&&p.push((/^on /.test(p[p.length-
1])?"":"on ")+y);if(u){var O=(h=/ ([\d.+]+)$/.exec(u))&&"/"==u.charAt(u.length-h[0].length-1);u={architecture:32,family:h&&!O?u.replace(h[0],""):u,version:h?h[1]:null,toString:function(){var a=this.version;return this.family+(a&&!O?" "+a:"")+(64==this.architecture?" 64-bit":"")}}}(h=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(L))&&!/\bi686\b/i.test(L)?(u&&(u.architecture=64,u.family=u.family.replace(RegExp(" *"+h),"")),q&&(/\bWOW64\b/i.test(a)||F&&/\w(?:86|32)$/.test(D.cpuClass||D.platform)&&!/\bWin64; x64\b/i.test(a))&&
p.unshift("32-bit")):u&&/^OS X/.test(u.family)&&"Chrome"==q&&39<=parseFloat(v)&&(u.architecture=64);a||(a=null);n={};n.description=a;n.layout=x&&x[0];n.manufacturer=C;n.name=q;n.prerelease=M;n.product=y;n.ua=a;n.version=q&&v;n.os=u||{architecture:null,family:null,version:null,toString:function(){return"null"}};n.parse=m;n.toString=function(){return this.description||""};n.version&&p.unshift(v);n.name&&p.unshift(q);u&&q&&(u!=String(u).split(" ")[0]||u!=q.split(" ")[0]&&!y)&&p.push(y?"("+u+")":"on "+
u);p.length&&(n.description=p.join(" "));return n}var f={"function":!0,object:!0},t=f[typeof window]&&window||this,n=f[typeof exports]&&exports;f=f[typeof module]&&module&&!module.nodeType&&module;var p=n&&f&&"object"==typeof global&&global;!p||p.global!==p&&p.window!==p&&p.self!==p||(t=p);var w=Math.pow(2,53)-1,r=/\bOpera/;p=Object.prototype;var z=p.hasOwnProperty,B=p.toString,D=m();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(t.platform=D,define(function(){return D})):n&&
f?d(D,function(a,b){n[b]=a}):t.platform=D}).call(this);var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var e=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var l=b.createElement("body");l.id="vpw-test-b";l.style.cssText="overflow:scroll";var g=b.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+e+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";l.appendChild(g);d.insertBefore(l,b.head);
a=7==g["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(l)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}
function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a="safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var e=getSize("Width");_checkOrientation(e,a);var b=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),d=CANVAS_WIDTH*b;b*=CANVAS_HEIGHT;if(b<a){var l=a-b;b+=l;d+=CANVAS_WIDTH/CANVAS_HEIGHT*l}else d<e&&(l=e-d,d+=l,b+=CANVAS_HEIGHT/CANVAS_WIDTH*l);l=a/2-b/2;var g=e/2-d/2,k=CANVAS_WIDTH/d;if(g*k<-EDGEBOARD_X||l*k<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
e/(CANVAS_WIDTH-2*EDGEBOARD_X)),d=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,l=(a-b)/2,g=(e-d)/2,k=CANVAS_WIDTH/d;s_iOffsetX=-1*g*k;s_iOffsetY=-1*l*k;0<=l&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*d,s_oStage.canvas.height=2*b,canvas.style.width=d+"px",canvas.style.height=b+"px",s_oStage.scaleX=s_oStage.scaleY=
2*Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",d+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=d,s_oStage.canvas.height=b,s_iScaleFactor=Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>l||(l=(a-b)/2);$("#canvas").css("top",l+"px");$("#canvas").css("left",g+"px");fullscreenHandler()}}
function _checkOrientation(a,e){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>e?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,e,b){var d=new createjs.Bitmap(a),l=new createjs.Shape;e&&b?l.graphics.beginFill("#fff").drawRect(0,0,e,b):l.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=l;return d}function createSprite(a,e,b,d,l,g){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-b,-d,l,g);a.hitArea=e;return a}
function randomFloatBetween(a,e,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(b))}function rotateVector2D(a,e){var b=e.getX()*Math.cos(a)+e.getY()*Math.sin(a),d=e.getX()*-Math.sin(a)+e.getY()*Math.cos(a);e.set(b,d)}function tweenVectorsOnX(a,e,b){return a+b*(e-a)}function shuffle(a){for(var e=a.length,b,d;0!==e;)d=Math.floor(Math.random()*e),--e,b=a[e],a[e]=a[d],a[d]=b;return a}
function bubbleSort(a){do{var e=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(e=a[b],a[b]=a[b+1],a[b+1]=e,e=!0)}while(e)}function compare(a,e){return a.index>e.index?-1:a.index<e.index?1:0}function easeLinear(a,e,b,d){return b*a/d+e}function easeInQuad(a,e,b,d){return b*(a/=d)*a+e}function easeInSine(a,e,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+e}function easeInCubic(a,e,b,d){return b*(a/=d)*a*a+e}
function getTrajectoryPoint(a,e){var b=new createjs.Point,d=(1-a)*(1-a),l=a*a;b.x=d*e.start.x+2*(1-a)*a*e.traj.x+l*e.end.x;b.y=d*e.start.y+2*(1-a)*a*e.traj.y+l*e.end.y;return b}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=parseFloat(a-60*e).toFixed(1);var b="";b=10>e?b+("0"+e+":"):b+(e+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,e){var b=getBounds(a,.9);var d=getBounds(e,.98);return calculateIntersection(b,d)}
function calculateIntersection(a,e){var b,d,l,g;var k=a.x+(b=a.width/2);var c=a.y+(d=a.height/2);var m=e.x+(l=e.width/2);var f=e.y+(g=e.height/2);k=Math.abs(k-m)-(b+l);c=Math.abs(c-f)-(d+g);return 0>k&&0>c?(k=Math.min(Math.min(a.width,e.width),-k),c=Math.min(Math.min(a.height,e.height),-c),{x:Math.max(a.x,e.x),y:Math.max(a.y,e.y),width:k,height:c,rect1:a,rect2:e}):null}
function getBounds(a,e){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,l=d.length,g;for(g=0;g<l;g++){var k=getBounds(d[g],1);k.x<b.x&&(b.x=k.x);k.y<b.y&&(b.y=k.y);k.x+k.width>b.x2&&(b.x2=k.x+k.width);k.y+k.height>b.y2&&(b.y2=k.y+k.height)}Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{if(a instanceof createjs.Bitmap){l=
a.sourceRect||a.image;g=l.width*e;var c=l.height*e}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){l=a.spriteSheet.getFrame(a.currentFrame);g=l.rect.width;c=l.rect.height;d=l.regX;var m=l.regY}else b.x=a.x||0,b.y=a.y||0;else b.x=a.x||0,b.y=a.y||0;d=d||0;g=g||0;m=m||0;c=c||0;b.regX=d;b.regY=m;l=a.localToGlobal(0-d,0-m);k=a.localToGlobal(g-d,c-m);g=a.localToGlobal(g-d,0-m);d=a.localToGlobal(0-d,c-m);b.x=
Math.min(Math.min(Math.min(l.x,k.x),g.x),d.x);b.y=Math.min(Math.min(Math.min(l.y,k.y),g.y),d.y);b.width=Math.max(Math.max(Math.max(l.x,k.x),g.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(l.y,k.y),g.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var e=a.length,b,d;0<e;)d=Math.floor(Math.random()*e),e--,b=a[e],a[e]=a[d],a[d]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[e]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var e="hidden";e in document?document.addEventListener("visibilitychange",a):(e="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(e="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(e="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var e=window.location.search.substring(1).split("&"),b=0;b<e.length;b++){var d=e[b].split("=");if(d[0]==a)return d[1]}}function playSound(a,e,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(e),s_aSounds[a].loop(b),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(e)}
function setMute(a,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(e)}function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.enabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},e,b,d,l,g,k;this.init=function(a,m,f){e={};d=b=0;l=a;g=m;k=f};this.addSprite=function(c,d){if(!a.hasOwnProperty(c)){var f=new Image;a[c]=e[c]={szPath:d,oSprite:f,bLoaded:!1};b++}};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){b=0;g.call(k)};this._onSpriteLoaded=function(){l.call(k);++d===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in e)e[a].oSprite.oSpriteLibrary=this,e[a].oSprite.szKey=
a,e[a].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},e[a].oSprite.onerror=function(a){var b=a.currentTarget;setTimeout(function(){e[b.szKey].oSprite.src=e[b.szKey].szPath},500)},e[a].oSprite.src=e[a].szPath};this.setLoaded=function(b){a[b].bLoaded=!0};this.isLoaded=function(b){return a[b].bLoaded};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=1920,CANVAS_HEIGHT=1080,EDGEBOARD_X=256,EDGEBOARD_Y=84,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,PRIMARY_FONT="arialbold",ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,TIME_ANIM_IDLE,ANIM_IDLE1_TIMESPEED,ANIM_IDLE2_TIMESPEED,ANIM_IDLE3_TIMESPEED,ANIM_SPIN_TIMESPEED,TIME_ANIM_WIN,ANIM_WIN1_TIMESPEED,ANIM_WIN2_TIMESPEED,TIME_ANIM_LOSE,STATE_IDLE=0,STATE_SPIN=1,STATE_WIN=2,STATE_LOSE=3,
LED_SPIN=3,MIN_FAKE_SPIN=3,WHEEL_SPIN_TIMESPEED=2600,START_CREDIT,START_BET,BET_OFFSET,MAX_BET,WHEEL_SETTINGS,AD_SHOW_COUNTER=[],BANK_CASH,WIN_OCCURRENCE,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SHOW_CREDITS,SEGMENT_ROT=18;TEXT_GAMEOVER="I'M SORRY, NO MORE CREDITS TO PLAY";TEXT_PLAY="PLAY";TEXT_CREDITS="CREDITS";TEXT_SPIN="SPIN";TEXT_PLUS="+";TEXT_MIN="-";TEXT_CURRENCY="$";TEXT_HELP1='CLICK ON "+" or "-" BUTTONS TO SELECT YOUR BET. PRIZE WILL VARY ACCORDING TO THE WAGER. THE MORE YOU BET, THE MORE YOU CAN WIN. WHEN YOU ARE READY, SPIN THE WHEEL TO PLAY!';
TEXT_HELP2="WHEN THE WHEEL STOPS SPINNING, YOU'LL BE SHOWN YOUR PRIZE!";TEXT_ALERT="wheel_settings PROBABILITY CHECK FAILED: win_occurence number sum must be 100! Please read paragraph in the documentation for more help.";var TEXT_CREDITS_DEVELOPED="DEVELOPED BY",TEXT_PRELOADER_CONTINUE="START";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,e,b,d,l,g,k,c,m,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){m.unload();f.removeAllChildren()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.addChild(t);t=s_oSpriteLibrary.getSprite("200x200");k=createBitmap(t);k.regX=.5*t.width;k.regY=.5*t.height;k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2-80;f.addChild(k);c=new createjs.Shape;c.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(k.x-100,k.y-100,200,200,10);f.addChild(c);k.mask=c;t=
s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(t);d.x=CANVAS_WIDTH/2-t.width/2;d.y=CANVAS_HEIGHT/2+70;f.addChild(d);a=t.width;e=t.height;l=new createjs.Shape;l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,1,e);f.addChild(l);d.mask=l;b=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2+120;b.textBaseline="alphabetic";b.textAlign="center";f.addChild(b);t=s_oSpriteLibrary.getSprite("but_start");m=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/
2+100,t,TEXT_PRELOADER_CONTINUE,"Arial","#000",36,!0,f);m.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);m.setVisible(!1);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.addChild(g);createjs.Tween.get(g).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(g);f.removeChild(g)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(c){b.text=c+"%";100===c&&(s_oMain._onRemovePreloader(),b.visible=
!1,d.visible=!1);l.graphics.clear();c=Math.floor(c*a/100);l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(d.x,d.y,c,e)};this._init()}
function CMain(a){var e,b=0,d=0,l=STATE_LOADING,g,k;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=30;navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();e=!0};this.soundLoaded=function(){b++;g.refreshLoader(Math.floor(b/d*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});
s_aSoundsInfo.push({path:"./sounds/",filename:"reel",loop:!0,volume:1,ingamename:"reel"});s_aSoundsInfo.push({path:"./sounds/",filename:"start_reel",loop:!1,volume:1,ingamename:"start_reel"});s_aSoundsInfo.push({path:"./sounds/",filename:"win",loop:!1,volume:1,ingamename:"win"});d+=s_aSoundsInfo.length;s_aSounds=[];for(var a=0;a<s_aSoundsInfo.length;a++)this.tryToLoadSound(s_aSoundsInfo[a],!1)};this.tryToLoadSound=function(a,b){setTimeout(function(){s_aSounds[a.ingamename]=new Howl({src:[a.path+a.filename+
".mp3"],autoplay:!1,preload:!0,loop:a.loop,volume:a.volume,onload:s_oMain.soundLoaded,onloaderror:function(a,b){for(var c=0;c<s_aSoundsInfo.length;c++)if(a===s_aSounds[s_aSoundsInfo[c].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[c],!0);break}},onplayerror:function(a){for(var b=0;b<s_aSoundsInfo.length;b++)if(a===s_aSounds[s_aSoundsInfo[b].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[b].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[b].ingamename].play()});
break}}})},b?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon",
"./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_spin","./sprites/but_spin.png");s_oSpriteLibrary.addSprite("but_plus","./sprites/but_plus.png");s_oSpriteLibrary.addSprite("wheel","./sprites/wheel.png");s_oSpriteLibrary.addSprite("leds","./sprites/leds.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");d+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;g.refreshLoader(Math.floor(b/d*100))};this._onAllImagesLoaded=function(){};this._onRemovePreloader=function(){g.unload();s_oMain.gotoMenu()};this.gotoMenu=function(){new CMenu;l=STATE_MENU};this.gotoGame=function(a){s_bEasyMode=a;k=new CGame(c);l=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;l=STATE_HELP};this.stopUpdate=function(){e=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");
!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();e=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==e){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);l===STATE_GAME&&k.update();
s_oStage.update(a)}};s_oMain=this;var c=a;ENABLE_CHECK_ORIENTATION=a.check_orientation;ENABLE_FULLSCREEN=a.fullscreen;SHOW_CREDITS=a.show_credits;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}var s_bMobile,s_bEasyMode,s_bAudioActive=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oCanvas,s_bFullscreen=!1,s_aSounds,s_aSoundsInfo;
function CTextButton(a,e,b,d,l,g,k,c,m){var f,t,n,p,w,r,z;this._init=function(a,b,c,d,e,l,g,m,k){f=!1;t=[];n=[];r=new createjs.Container;r.x=a;r.y=b;r.cursor="pointer";k.addChild(r);m?(z=createBitmap(c),r.addChild(z),r.regX=c.width/2):(a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height},animations:{state_true:[0],state_false:[1]}}),z=createSprite(a,"state_false",0,0,c.width/2,c.height),r.addChild(z),new CTLText(r,20,20,c.width/2-40,c.height-40,g,"center",l,e,1,10,10,d,
!0,!0,!1,!1),r.regX=c.width/4);r.regY=c.height/2;this._initListener()};this.unload=function(){r.off("mousedown",p);r.off("pressup",w);m.removeChild(r)};this.setVisible=function(a){r.visible=a};this._initListener=function(){p=r.on("mousedown",this.buttonDown);w=r.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){t[a]=b;n[a]=c};this.buttonRelease=function(){f||(r.scaleX=1,r.scaleY=1,playSound("click",1,!1),t[ON_MOUSE_UP]&&t[ON_MOUSE_UP].call(n[ON_MOUSE_UP]))};this.buttonDown=function(){f||
(r.scaleX=.9,r.scaleY=.9,t[ON_MOUSE_DOWN]&&t[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN]))};this.enable=function(){f=!1;c||z.gotoAndStop("state_true")};this.disable=function(){f=!0;c||z.gotoAndStop("state_false")};this.setPosition=function(a,b){r.x=a;r.y=b};this.setX=function(a){r.x=a};this.setY=function(a){r.y=a};this.getButtonImage=function(){return r};this.getX=function(){return r.x};this.getY=function(){return r.y};this._init(a,e,b,d,l,g,k,c,m);return this}
function CToggle(a,e,b,d,l){var g,k,c,m,f,t;this._init=function(a,b,d,f){k=[];c=[];var e=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});g=f;t=createSprite(e,"state_"+g,d.width/2/2,d.height/2,d.width/2,d.height);t.x=a;t.y=b;t.stop();t.cursor="pointer";n.addChild(t);this._initListener()};this.unload=function(){t.off("mousedown",m);t.off("pressup",f);n.removeChild(t)};this._initListener=function(){m=
t.on("mousedown",this.buttonDown);f=t.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){k[a]=b;c[a]=d};this.setActive=function(a){g=a;t.gotoAndStop("state_"+g)};this.buttonRelease=function(){t.scaleX=1;t.scaleY=1;playSound("click",1,!1);g=!g;t.gotoAndStop("state_"+g);k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(c[ON_MOUSE_UP],g)};this.buttonDown=function(){t.scaleX=.9;t.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN])};this.setPosition=function(a,b){t.x=a;t.y=b};var n=
l;this._init(a,e,b,d)}
function CGfxButton(a,e,b){var d,l,g,k,c;this._init=function(a,b,e){d=[];l=[];c=createBitmap(e);c.x=a;c.y=b;c.regX=e.width/2;c.regY=e.height/2;c.cursor="pointer";s_oStage.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown",g);c.off("pressup",k);s_oStage.removeChild(c)};this.setVisible=function(a){c.visible=a};this._initListener=function(){g=c.on("mousedown",this.buttonDown);k=c.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){d[a]=b;l[a]=c};this.buttonRelease=
function(){c.scaleX=1;c.scaleY=1;playSound("click",1,!1);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};this.buttonDown=function(){c.scaleX=.9;c.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setPosition=function(a,b){c.x=a;c.y=b};this.setX=function(a){c.x=a};this.setY=function(a){c.y=a};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this._init(a,e,b);return this}
function CMenu(){var a,e,b,d,l,g,k=null,c=null,m,f,t,n,p,w;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(f);var r=s_oSpriteLibrary.getSprite("but_play");t=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-190,r,TEXT_PLAY,PRIMARY_FONT,"#ffffff",70,!1,s_oStage);t.enable();t.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);r=s_oSpriteLibrary.getSprite("but_credits");SHOW_CREDITS?(a=CANVAS_WIDTH-r.height/2-10,e=r.height/2+10,w=new CGfxButton(a,e,r,s_oStage),
w.addEventListener(ON_MOUSE_UP,this._onCredits,this),r=s_oSpriteLibrary.getSprite("audio_icon"),l=a-r.width/2-10):(r=s_oSpriteLibrary.getSprite("audio_icon"),l=CANVAS_WIDTH-r.height/2-10);g=r.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p=new CToggle(l,g,r,s_bAudioActive,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);r=window.document;var z=r.documentElement;k=z.requestFullscreen||z.mozRequestFullScreen||z.webkitRequestFullScreen||z.msRequestFullscreen;c=r.exitFullscreen||
r.mozCancelFullScreen||r.webkitExitFullscreen||r.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(k=!1);k&&screenfull.enabled&&(r=s_oSpriteLibrary.getSprite("but_fullscreen"),b=r.width/4+10,d=r.height/2+10,m=new CToggle(b,d,r,s_bFullscreen,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));n=new createjs.Shape;n.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(n);createjs.Tween.get(n).to({alpha:0},1E3).call(function(){n.visible=!1});this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.unload=function(){t.unload();t=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;SHOW_CREDITS&&(w.unload(),w=null);k&&screenfull.enabled&&m.unload();s_oStage.removeChild(f);s_oMenu=f=null};this.refreshButtonPos=function(c,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(l-c,f+g);SHOW_CREDITS&&w.setPosition(a-c,f+e);k&&screenfull.enabled&&m.setPosition(b+c,d+f)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};
this.resetFullscreenBut=function(){m.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?c.call(window.document):k.call(window.document.documentElement);sizeHandler()};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoGame()};this._onCredits=function(){new CCreditsPanel};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var e,b,d,l,g,k,c,m,f,t,n,p,w,r=null,z,B;this._init=function(){k=1;d=b=0;c=START_BET;m=START_CREDIT;f=-1;g=STATE_IDLE;t=0;n=BANK_CASH;p=[];for(var a=0,r=0;r<WHEEL_SETTINGS.length;r++)a+=WHEEL_SETTINGS[r].win_occurence;100!==a?(a=createBitmap(s_oSpriteLibrary.getSprite("msg_box")),s_oStage.addChild(a),a=new createjs.Text(TEXT_ALERT,"50px "+PRIMARY_FONT,"#ffffff"),a.x=CANVAS_WIDTH/2,a.y=CANVAS_HEIGHT/2-200,a.textAlign="center",a.textBaseline="middle",a.lineWidth=900,s_oStage.addChild(a)):
(e=!0,z=new CWheel(1198,540),a=createBitmap(s_oSpriteLibrary.getSprite("bg_game")),s_oStage.addChild(a),B=new CLeds(1198,540),l=B.getState(),w=new CInterface,new CHelpPanel,this._initProbability(),m<START_BET&&this.gameOver())};this._initProbability=function(){for(var a=[],b=0;b<WHEEL_SETTINGS.length;b++)a[b]=WHEEL_SETTINGS[b].win_occurence;for(b=0;b<a.length;b++)for(var c=0;c<a[b];c++)p.push(b)};this.modifyBonus=function(a){c="plus"===a?c+BET_OFFSET:c-BET_OFFSET;c=parseFloat(c.toFixed(2));if(c>MAX_BET)c-=
BET_OFFSET,k=1;else if(c<START_BET)c+=BET_OFFSET,k=1;else if(c>m){c-=BET_OFFSET;return}k=c/START_BET;k=k.toFixed(2);w.refreshBet(c);z.clearText();z.setText(k)};this.tryShowAd=function(){t++;t===AD_SHOW_COUNTER&&(t=0,$(s_oMain).trigger("show_interlevel_ad"))};this.spinWheel=function(){w.disableSpin(!0);g=STATE_SPIN;d=0;this.setNewRound();w.refreshMoney(0);m-=c;n+=c;m=parseFloat(m.toFixed(2));n=parseFloat(n.toFixed(2));w.refreshCredit(m);for(var a,b=[],e=0;e<p.length;e++)a=WHEEL_SETTINGS[p[e]].prize*
k,a<=n&&b.push({prize:a,index:e});b=b[Math.floor(Math.random()*b.length)].index;f=p[b];a=MIN_FAKE_SPIN+Math.floor(3*Math.random());e=SEGMENT_ROT-3;e=-e/2+Math.random()*e;b=(360-z.getDegree()+p[b]*SEGMENT_ROT+e)%360;b=360*a+b;z.clearText();z.setText(k);z.spin(b,a);$(s_oMain).trigger("bet_placed",c)};this.setNewRound=function(){0>f||(w.refreshCredit(m),w.clearMoneyPanel(),f=-1)};this.releaseWheel=function(){this.tryShowAd();w.disableSpin(!1);w.refreshMoney(WHEEL_SETTINGS[f].prize*k);m+=WHEEL_SETTINGS[f].prize*
k;n-=WHEEL_SETTINGS[f].prize*k;$(s_oMain).trigger("save_score",[m]);w.refreshCredit(m);w.animWin();m<START_BET&&this.gameOver();k>m/START_BET&&(k=Math.floor(m/START_BET),c=k*START_BET,w.refreshBet(c));0>=WHEEL_SETTINGS[f].prize?(g=STATE_LOSE,playSound("game_over",1,!1)):(g=STATE_WIN,playSound("win",1,!1))};this.getCurColor=function(){return z.getColor()};this.unload=function(){stopSound("reel");e=!1;w.unload();null!==r&&r.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=
function(){$(s_oMain).trigger("save_score",[m]);$(s_oMain).trigger("share_event",m);this.unload();s_oMain.gotoMenu()};this.gameOver=function(){r=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));r.show()};this._animLedIdle=function(){b+=s_iTimeElaps;if(b>TIME_ANIM_IDLE){b=0;for(var a=Math.floor(Math.random()*B.getNumAnim());a===l;)a=Math.floor(Math.random()*B.getNumAnim());B.changeAnim(a);l=a}};this._animLedSpin=function(){B.changeAnim(LED_SPIN);g=-1};this._animLedWin=function(){0===d?(B.changeAnim(4+
Math.round(Math.random())),B.setWinColor(this.getCurColor())):d>TIME_ANIM_WIN&&(b=TIME_ANIM_IDLE,g=STATE_IDLE,this.setNewRound(),d=0);d+=s_iTimeElaps};this._animLedLose=function(){0===d?(B.changeAnim(6),B.setWinColor(this.getCurColor())):d>TIME_ANIM_LOSE&&(b=TIME_ANIM_IDLE,g=STATE_IDLE,this.setNewRound(),d=0);d+=s_iTimeElaps};this.update=function(){if(e)switch(B.update(),g){case STATE_IDLE:this._animLedIdle();break;case STATE_SPIN:this._animLedSpin();break;case STATE_WIN:this._animLedWin();break;
case STATE_LOSE:this._animLedLose()}};s_oGame=this;WHEEL_SETTINGS=a.wheel_settings;START_CREDIT=a.start_credit;START_BET=a.start_bet;BET_OFFSET=a.bet_offset;MAX_BET=a.max_bet;TIME_ANIM_IDLE=a.anim_idle_change_frequency;ANIM_IDLE1_TIMESPEED=a.led_anim_idle1_timespeed;ANIM_IDLE2_TIMESPEED=a.led_anim_idle2_timespeed;ANIM_IDLE3_TIMESPEED=a.led_anim_idle3_timespeed;ANIM_SPIN_TIMESPEED=a.led_anim_spin_timespeed;TIME_ANIM_WIN=a.led_anim_win_duration;ANIM_WIN1_TIMESPEED=a.led_anim_win1_timespeed;ANIM_WIN2_TIMESPEED=
a.led_anim_win2_timespeed;TIME_ANIM_LOSE=a.led_anim_lose_duration;AD_SHOW_COUNTER=a.ad_show_counter;BANK_CASH=a.bank_cash;ENABLE_FULLSCREEN=a.fullscreen;this._init()}var s_oGame;
function CVector2(a,e){var b,d;this._init=function(a,e){b=a;d=e};this.add=function(a,e){b+=a;d+=e};this.addV=function(a){b+=a.getX();d+=a.getY()};this.scalarDivision=function(a){b/=a;d/=a};this.subV=function(a){b-=a.getX();d-=a.getY()};this.scalarProduct=function(a){b*=a;d*=a};this.invert=function(){b*=-1;d*=-1};this.dotProduct=function(a){return b*a.getX()+d*a.getY()};this.set=function(a,e){b=a;d=e};this.setV=function(a){b=a.getX();d=a.getY()};this.length=function(){return Math.sqrt(b*b+d*d)};this.length2=
function(){return b*b+d*d};this.normalize=function(){var a=this.length();0<a&&(b/=a,d/=a)};this.getNormalize=function(a){this.length();a.set(b,d);a.normalize()};this.rot90CCW=function(){var a=b;b=-d;d=a};this.rot90CW=function(){var a=b;b=d;d=-a};this.getRotCCW=function(a){a.set(b,d);a.rot90CCW()};this.getRotCW=function(a){a.set(b,d);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);d=Math.ceil(d)};this.round=function(){b=Math.round(b);d=Math.round(d)};this.toString=function(){return"Vector2: "+b+", "+
d};this.print=function(){trace("Vector2: "+b+", "+d)};this.getX=function(){return b};this.getY=function(){return d};this._init(a,e)}
function CFormatText(a,e,b,d){var l,g,k,c;this._init=function(a,b,d,e){l=0;c=new createjs.Container;c.x=a;c.y=b;e.addChild(c);a=85;b=a/20;for(e=0;e<d.length;e++){var f=a+"px";g=new createjs.Text;g.text=d[e];g.font=f+" "+PRIMARY_FONT;g.color="#000000";g.textAlign="left";g.textBaseline="middle";g.x=l+2;g.y=6;c.addChild(g);k=new createjs.Text;k.text=d[e];k.font=f+" "+PRIMARY_FONT;k.color="#ffffff";k.textAlign="left";k.textBaseline="middle";k.x=l;k.y=4;c.addChild(k);l+=k.getMeasuredWidth()+b;a-=9}c.cache(0,
-c.getBounds().height/2,c.getBounds().width,c.getBounds().height)};this.unload=function(){d.removeChild(c)};this.rotateText=function(a){c.rotation=a};this._init(a,e,b,d)}
function CInterface(){var a,e,b,d,l,g,k=null,c=null,m,f,t,n,p,w,r,z,B,D,I,G;this._init=function(){I=this;r=0;var A=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-A.height/2-10;d=A.height/2+10;t=new CGfxButton(b,d,A,!0);t.addEventListener(ON_MOUSE_UP,this._onExit,this);a=CANVAS_WIDTH-A.width/2-100;e=A.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)A=s_oSpriteLibrary.getSprite("audio_icon"),f=new CToggle(a,e,A,s_bAudioActive,s_oStage),f.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);A=window.document;var J=A.documentElement;k=J.requestFullscreen||J.mozRequestFullScreen||J.webkitRequestFullScreen||J.msRequestFullscreen;c=A.exitFullscreen||A.mozCancelFullScreen||A.webkitExitFullscreen||A.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(k=!1);k&&screenfull.enabled&&(A=s_oSpriteLibrary.getSprite("but_fullscreen"),l=A.width/4+10,g=A.height/2+10,m=new CToggle(l,g,A,s_bFullscreen,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));A=s_oSpriteLibrary.getSprite("but_spin");
n=new CTextButton(500,CANVAS_HEIGHT-190,A,TEXT_SPIN,PRIMARY_FONT,"#ffffff",70,!1,s_oStage);n.enable();n.addEventListener(ON_MOUSE_UP,this._onButSpinRelease,this);A=s_oSpriteLibrary.getSprite("but_plus");p=new CTextButton(650,CANVAS_HEIGHT-320,A,TEXT_PLUS,PRIMARY_FONT,"#ffffff",70,!1,s_oStage);p.enable();p.addEventListener(ON_MOUSE_UP,this._onButPlusRelease,this);A=s_oSpriteLibrary.getSprite("but_plus");w=new CTextButton(350,CANVAS_HEIGHT-320,A,TEXT_MIN,PRIMARY_FONT,"#ffffff",70,!1,s_oStage);w.enable();
w.addEventListener(ON_MOUSE_UP,this._onButMinRelease,this);new CTLText(s_oStage,282,132,450,100,140,"center","#000000",PRIMARY_FONT,1,2,2,TEXT_CREDITS,!0,!0,!1,!1);new CTLText(s_oStage,280,130,450,100,140,"center","#fff",PRIMARY_FONT,1,2,2,TEXT_CREDITS,!0,!0,!1,!1);z=new CTLText(s_oStage,310,284,370,90,100,"left","#fff",PRIMARY_FONT,1,2,2,TEXT_CURRENCY+START_CREDIT.toFixed(2),!0,!0,!1,!1);B=new CTLText(s_oStage,310,486,326,110,100,"left","#fff",PRIMARY_FONT,1,2,2,TEXT_CURRENCY+"0.00",!0,!0,!1,!1);
G=new CTLText(s_oStage,310,486,326,110,100,"left","yellow",PRIMARY_FONT,1,2,2,TEXT_CURRENCY+"0.00",!0,!0,!1,!1);G.setAlpha(r);D=new CTLText(s_oStage,410,730,180,60,70,"center","#fff",PRIMARY_FONT,1,2,2,TEXT_CURRENCY+START_BET,!0,!0,!1,!1);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),f=null;t.unload();n.unload();k&&screenfull.enabled&&m.unload();s_oInterface=null};this.refreshCredit=function(a){z.refreshText(TEXT_CURRENCY+
a.toFixed(2))};this.clearMoneyPanel=function(){G.setAlpha(0);createjs.Tween.removeTweens(G.getText())};this.refreshMoney=function(a){B.refreshText(TEXT_CURRENCY+a.toFixed(2));G.refreshText(TEXT_CURRENCY+a.toFixed(2))};this.refreshBet=function(a){D.refreshText(TEXT_CURRENCY+a)};this.animWin=function(){r=1===r?0:1;createjs.Tween.get(G.getText()).to({alpha:r},150,createjs.Ease.cubicOut).call(function(){I.animWin()})};this._onButSpinRelease=function(){s_oGame.spinWheel()};this._onButPlusRelease=function(){s_oGame.modifyBonus("plus")};
this._onButMinRelease=function(){s_oGame.modifyBonus("min")};this.disableSpin=function(a){!0===a?(n.disable(),p.disable(),w.disable()):(n.enable(),p.enable(),w.enable())};this.refreshButtonPos=function(c,n){t.setPosition(b-c,n+d);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||f.setPosition(a-c,n+e);k&&screenfull.enabled&&m.setPosition(l+c,g+n)};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){m.setActive(s_bFullscreen)};this._onFullscreenRelease=
function(){s_bFullscreen?c.call(window.document):k.call(window.document.documentElement);sizeHandler()};this._onExit=function(){$(s_oMain).trigger("end_session");s_oGame.onExit()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,e;this._init=function(){e=new createjs.Container;e.alpha=0;s_oStage.addChild(e);var b=this;a=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));e.addChild(a);new CTLText(e,CANVAS_WIDTH/2-98,CANVAS_HEIGHT/2-312,600,280,70,"center","#000000",PRIMARY_FONT,1,2,2,TEXT_HELP1,!0,!0,!0,!1);new CTLText(e,CANVAS_WIDTH/2-100,CANVAS_HEIGHT/2-310,600,280,70,"center","#fff",PRIMARY_FONT,1,2,2,TEXT_HELP1,!0,!0,!0,!1);new CTLText(e,CANVAS_WIDTH/2-498,CANVAS_HEIGHT/2+102,600,180,70,"center",
"#000000",PRIMARY_FONT,1,2,2,TEXT_HELP2,!0,!0,!0,!1);new CTLText(e,CANVAS_WIDTH/2-500,CANVAS_HEIGHT/2+100,600,180,70,"center","#fff",PRIMARY_FONT,1,2,2,TEXT_HELP2,!0,!0,!0,!1);createjs.Tween.get(e).to({alpha:1},700);e.on("pressup",function(){b._onExitHelp()})};this.unload=function(){s_oStage.removeChild(e);var a=this;e.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){b.unload()};var b=this;this._init()}
function CEndPanel(a){var e,b,d,l;this._init=function(a){b=new createjs.Container;b.alpha=0;b.visible=!1;s_oStage.addChild(b);e=createBitmap(a);b.addChild(e);d=new CTLText(b,CANVAS_WIDTH/2-398,222,800,600,70,"center","#000",PRIMARY_FONT,1,20,20,"",!0,!0,!0,!1);l=new CTLText(b,CANVAS_WIDTH/2-400,220,800,600,70,"center","#fff",PRIMARY_FONT,1,20,20,"",!0,!0,!0,!1)};this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(){playSound("game_over",
1,!1);$(s_oMain).trigger("show_interlevel_ad");d.refreshText(TEXT_GAMEOVER);l.refreshText(TEXT_GAMEOVER);b.visible=!0;var a=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){a._initListener()})};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);$(s_oMain).trigger("end_session");s_oGame.onExit()};this._init(a);return this}
function CWheel(a,e){var b,d,l,g,k;this._init=function(a,e){b=[];d=[];l=[];for(var c=0;c<WHEEL_SETTINGS.length;c++)l[c]=WHEEL_SETTINGS[c].prize;this._initColors();c=s_oSpriteLibrary.getSprite("wheel");k=new createjs.Container;k.x=a;k.y=e;s_oStage.addChild(k);g=createBitmap(c);g.regX=c.width/2;g.regY=c.height/2;k.addChild(g);g.cache(0,0,c.width,c.height);this.setText(1)};this.unload=function(){s_oStage.removeChild(k)};this._initColors=function(){for(var a=0;9>a;a++)d[0]="violet";for(a=351;360>=a;a++)d[a]=
"violet";for(var b=0;4>b;b++)for(a=9+b*SEGMENT_ROT*5;a<27+b*SEGMENT_ROT*5;a++)d[a]="blue";for(b=0;4>b;b++)for(a=27+b*SEGMENT_ROT*5;a<45+b*SEGMENT_ROT*5;a++)d[a]="green";for(b=0;4>b;b++)for(a=45+b*SEGMENT_ROT*5;a<63+b*SEGMENT_ROT*5;a++)d[a]="yellow";for(b=0;4>b;b++)for(a=63+b*SEGMENT_ROT*5;a<81+b*SEGMENT_ROT*5;a++)d[a]="red";for(b=0;3>b;b++)for(a=81+b*SEGMENT_ROT*5;a<=99+b*SEGMENT_ROT*5;a++)d[a]="violet";for(a=315;333>=a;a++)d[a]="white"};this.setText=function(a){for(var c=new CVector2(-355,3),d=SEGMENT_ROT,
e=Math.PI*SEGMENT_ROT/180,g=0;g<l.length;g++){var p=(l[g]*a).toFixed(2);b[g]=new CFormatText(c.getX(),c.getY(),TEXT_CURRENCY+p,k);b[g].rotateText(-d*g);rotateVector2D(e,c)}};this.clearText=function(){for(var a=0;a<l.length;a++)b[a].unload()};this.spin=function(a,b){playSound("start_reel",1,!1);playSound("reel",.1,!0);createjs.Tween.get(k).to({rotation:k.rotation+a},WHEEL_SPIN_TIMESPEED*b,createjs.Ease.quartOut).call(function(){k.rotation%=360;s_oGame.releaseWheel();!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||stopSound("reel")})};this.getDegree=function(){return k.rotation};this.getColor=function(){return d[Math.round(k.rotation)]};this._init(a,e)}
function CLeds(a,e){var b,d,l,g,k,c,m,f,t;this._init=function(a,b){k=3;l=Math.floor(Math.random()*k);g=0;f=[];t=new createjs.Container;t.x=a;t.y=b;s_oStage.addChild(t);var c={images:[s_oSpriteLibrary.getSprite("leds")],frames:{width:90,height:90,regX:45,regY:45},animations:{off:[0],white:[1],green:[2],blue:[3],violet:[4],red:[5],yellow:[6]}};c=new createjs.SpriteSheet(c);for(var d=new CVector2(-427,0),e=360/WHEEL_SETTINGS.length*Math.PI/180,n=0;n<WHEEL_SETTINGS.length;n++)f[n]=createSprite(c,"off",
0,0,90,90),f[n].x=d.getX(),f[n].y=d.getY(),rotateVector2D(e,d),t.addChild(f[n]);f[0].visible=!1};this.unload=function(){s_oStage.removeChild(t)};this.setWinColor=function(a){b=a};this.getState=function(){return l};this.getNumAnim=function(){return k};this.changeAnim=function(a){g=0;l=a;for(a=0;a<f.length;a++)f[a].gotoAndStop("off")};this.animIdle0=function(){g+=s_iTimeElaps;if(0<=g&&g<ANIM_IDLE1_TIMESPEED/2)for(var a=0;a<f.length;a++)0===a%2?f[a].gotoAndStop("white"):f[a].gotoAndStop("off");else if(g>=
ANIM_IDLE1_TIMESPEED/2&&g<ANIM_IDLE1_TIMESPEED)for(a=0;a<f.length;a++)0===a%2?f[a].gotoAndStop("off"):f[a].gotoAndStop("white");else g=0};this.animIdle1=function(){0===g&&(c=0,f[c].gotoAndStop("white"),f[f.length/4].gotoAndStop("white"),f[f.length/2].gotoAndStop("white"),f[3*f.length/4].gotoAndStop("white"));g+=s_iTimeElaps;g>ANIM_IDLE2_TIMESPEED&&(c===f.length/4&&(c=0,g=1),0===c?(f[f.length-1].gotoAndStop("off"),f[0].gotoAndStop("white"),f[f.length/4-1].gotoAndStop("off"),f[f.length/4].gotoAndStop("white"),
f[f.length/2-1].gotoAndStop("off"),f[f.length/2].gotoAndStop("white"),f[3*f.length/4-1].gotoAndStop("off"),f[3*f.length/4].gotoAndStop("white")):(f[c-1].gotoAndStop("off"),f[c].gotoAndStop("white"),f[f.length/4+c-1].gotoAndStop("off"),f[f.length/4+c].gotoAndStop("white"),f[f.length/2+c-1].gotoAndStop("off"),f[f.length/2+c].gotoAndStop("white"),f[3*f.length/4+c-1].gotoAndStop("off"),f[3*f.length/4+c].gotoAndStop("white")),c++,g=1)};this.animIdle2=function(){0===g&&(c=0,m=f.length/2,f[c].gotoAndStop("white"),
f[m].gotoAndStop("white"));g+=s_iTimeElaps;g>ANIM_IDLE3_TIMESPEED&&(c===f.length/2&&(c=0,m=f.length/2,g=1),0===c?(f[f.length-1].gotoAndStop("off"),f[1].gotoAndStop("off"),f[0].gotoAndStop("white"),f[f.length/2+1].gotoAndStop("off"),f[f.length/2-1].gotoAndStop("off"),f[f.length/2].gotoAndStop("white")):(f[c-1].gotoAndStop("off"),f[c].gotoAndStop("white"),1!==c&&f[f.length-c+1].gotoAndStop("off"),f[f.length-c].gotoAndStop("white"),f[m+1].gotoAndStop("off"),f[m].gotoAndStop("white"),f[f.length-m-1].gotoAndStop("off"),
0!==m&&f[f.length-m].gotoAndStop("white")),c++,m--,g=1)};this.animSpin0=function(){0===g&&(c=Math.floor(Math.random()*f.length),f[c].gotoAndStop("white"));g+=s_iTimeElaps;g>ANIM_SPIN_TIMESPEED&&(0>c&&(c=f.length-1,g=1),c===f.length-1?(f[0].gotoAndStop("off"),f[f.length-1].gotoAndStop("white")):(f[c+1].gotoAndStop("off"),f[c].gotoAndStop("white")),c--,g=1)};this.animWin0=function(){g+=s_iTimeElaps;if(0<=g&&g<ANIM_WIN1_TIMESPEED/2)for(var a=0;a<f.length;a++)0===a%2?f[a].gotoAndStop(b):f[a].gotoAndStop("off");
else if(g>=ANIM_WIN1_TIMESPEED/2&&g<ANIM_WIN1_TIMESPEED)for(a=0;a<f.length;a++)0===a%2?f[a].gotoAndStop("off"):f[a].gotoAndStop(b);else g=0};this.animWin1=function(){0===g&&(c=0,m=f.length/2,d=b,f[c].gotoAndStop(d),f[m].gotoAndStop(d));g+=s_iTimeElaps;g>ANIM_WIN2_TIMESPEED&&(c>f.length/4&&(c=0,m=f.length/2,g=1,d=d===b?"off":b),0===c?(f[0].gotoAndStop(d),f[f.length/2].gotoAndStop(d)):c<=f.length/4&&(f[c].gotoAndStop(d),f[f.length-c].gotoAndStop(d),f[m].gotoAndStop(d),0!==m&&f[f.length-m].gotoAndStop(d)),
c++,m--,g=1)};this.animLose=function(){for(var a=0;a<f.length;a++)f[a].gotoAndStop(b);l=-1};this.update=function(){switch(l){case 0:this.animIdle0();break;case 1:this.animIdle1();break;case 2:this.animIdle2();break;case 3:this.animSpin0();break;case 4:this.animWin0();break;case 5:this.animWin1();break;case 6:this.animLose()}};this._init(a,e)}
function CCreditsPanel(){var a,e,b,d,l,g,k,c;this._init=function(){c=new createjs.Container;s_oStage.addChild(c);var m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));c.addChild(m);m=s_oSpriteLibrary.getSprite("msg_box");b=createBitmap(m);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;b.regX=m.width/2;b.regY=m.height/2;c.addChild(b);g=new createjs.Shape;g.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=.01;e=g.on("click",this._onLogoButRelease);c.addChild(g);m=s_oSpriteLibrary.getSprite("but_exit");
a=CANVAS_WIDTH/2+570;d=new CGfxButton(a,254,m,c);d.addEventListener(ON_MOUSE_UP,this.unload,this);l=new createjs.Text(TEXT_CREDITS_DEVELOPED,"46px "+PRIMARY_FONT,"#ffffff");l.x=CANVAS_WIDTH/2;l.y=430;l.textAlign="center";c.addChild(l);m=s_oSpriteLibrary.getSprite("logo_credits");var f=createBitmap(m);f.regX=m.width/2;f.regY=m.height/2;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;c.addChild(f);k=new createjs.Text("WWW.CODETHISLAB.COM","35px "+PRIMARY_FONT,"#ffffff");k.x=CANVAS_WIDTH/2;k.y=600;k.textAlign=
"center";c.addChild(k)};this.unload=function(){g.off("click",e);d.unload();d=null;s_oStage.removeChild(c)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,e,b,d){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,e,b,d))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},setPos:function(a,e){this._x=a;this._y=e;this._oText.x=a;this._oText.y=e},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},
getY:function(){return this._y},getFontSize:function(){return this._iFontSize},refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,e,b,d,l,g,k,c,m,f,t,n,p,w,r,z,B){this._oContainer=a;this._x=e;this._y=b;this._iWidth=d;this._iHeight=l;this._bMultiline=z;this._iFontSize=g;this._szAlign=k;this._szColor=c;this._szFont=m;this._iPaddingH=t;this._iPaddingV=n;this._bVerticalAlign=r;this._bFitText=w;this._bDebug=B;this._oDebugShape=null;this._fLineHeightFactor=f;this._oText=null;p&&this.__createText(p)};